### PR TITLE
Fix packer output location

### PR DESCRIPTION
**Pull request by ryd**
* Set parameter for packer to stub folder
* payload got loaded in stub via embed

### CODE REVIEW

**Review by 0dayCTF — COMMENTED** [review]
While making your change, running Kali latest.
```
# github.com/vyrus001/go-mimikatz/stub
stub/stub.go:15:17: too many arguments in call to syscall.Syscall
        have (uintptr, number, number, number, number)
        want (uintptr, uintptr, uintptr, uintptr)
make.go:4: running "go": exit status 2
```

**Comment by ryd** [comment]
@0dayCTF This msg/error shows up when compiling on any other OS than Windows.

**Comment by 0dayCTF** [comment]
I tried on both, still getting an error. I’ll play with it, thank you.

**Comment by vyrus001** [comment]
the underlying issue that caused this problem has been addressed, but also the compile mechanism has been altered for additional defender evasion so this PR isn't relevant any more

**Comment by vyrus001** [comment]
Oh, I missed the fact that you are not compiling ok windows, yea the
syscall func format is different on nix / Darwin. I can cook a fix today

**Pull request closed without merging**
